/**
 * Minimal module declaration for the Rust-generated WebAssembly package.
 * Real type definitions should be generated by `wasm-bindgen` when available.
 */
declare module '../../rust-wasm/pkg/representatodo_wasm' {
  export function greet(name: string): string;
}
